services:
  api:
    image: ghcr.io/oscarhermawan17/eksportir-api:latest
    build:
      context: ./eksportir-api
    container_name: eksportir-api
    restart: unless-stopped
    env_file: ./eksportir-api/.env
    networks:
      - eksportir-net

  nginx:
    image: nginx:alpine
    container_name: eksportir-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - api
      - umkm-api
    networks:
      - eksportir-net

  # ── UMKM ONLINE ──────────────────────────────────────────────────────────────
  umkm-api:
    image: ghcr.io/oscarhermawan17/online-shop-api:latest
    container_name: umkm-api
    restart: unless-stopped
    env_file: ./umkm.env
    expose:
      - "4000"
    networks:
      - eksportir-net
  # ─────────────────────────────────────────────────────────────────────────────

networks:
  eksportir-net:
    driver: bridge
